{% set name = "rbloom" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ea6804f837c14d8ff041b07df8666798ac1ddcab709e139d06b0ea69d627f827

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - pip               # [build_platform != target_platform]
    - python            # [build_platform != target_platform]
    - maturin >=1.0,<2  # [build_platform != target_platform]
  host:
    - pip
    - python
    - maturin >=1.0,<2
  run:
    - python

test:
  imports:
    - rbloom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KenanHanke/rbloom
  summary: A fast, simple and lightweight Bloom filter library for Python, implemented in Rust
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
